package org.acme.travels

import org.acme.vegatables.guard.TransactionEvent;
import org.acme.vegatables.guard.VegetableEvent;


rule "Match events"

when
    $tx : TransactionEvent()
    $veg : VegetableEvent(source.transactionId == $tx.source.transactionId)
then
    System.out.println($veg + " is matched with transaction data");
    $veg.setMatched(true);
    
    delete($tx);
    delete($veg);
end
